### ISSUE TITLE
[Bug] App crashes on Linux

### ISSUE THREAD

**Issue by BalassaMarton** [morganstanley/dotnet-please#47]
Invoke any command or just `please` on Linux, you will get below error:

```
Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.get_CursorVisible()
   at System.Console.get_CursorVisible()
   at DotNetPlease.App.ExecuteAsync(String[] args) in /home/runner/work/dotnet-please/dotnet-please/DotNetPlease/App.cs:line 70
   at DotNetPlease.Program.<Main>(String[] args)
```

Tested on RHEL 7.

**Comment by psmulovics** [comment]
duplicate of #109

**Comment by BalassaMarton** [comment]
Just  a heads up, I started working on this, however the `Console` issue is just one of the problems. Now I'm getting this from an MSBuild assembly:
```
Invalid static method invocation syntax: "[MSBuild]::SubstringByAsciiChars($(MSBuildProjectFile), 0, 8)". Method '[MSBuild]::SubstringByAsciiChars' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order.
```
Will investigate...
