### ISSUE TITLE
[Bug] Crashes if you have a preview SDK installed

### ISSUE THREAD

**Issue by jwm01cg** [morganstanley/dotnet-please#93]
Hi - thanks for this tool! Just wanted to raise the following issue. I ran the following command:
```
$ please consolidate packages
```
and I got this 
```
dotnet-please from Morgan Stanley
2.1.0
Visit us at https://github.com/morganstanley

Unhandled exception. System.TypeInitializationException: The type initializer for 'DotNetPlease.Helpers.MSBuildHelper' threw an exception.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at DotNetPlease.Helpers.MSBuildHelper.<>c.<LocateMSBuild>b__48_0(Match m) in /home/runner/work/dotnet-please/dotnet-please/DotNetPlease/Helpers/MSBuildHelper.cs:line 537
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DotNetPlease.Helpers.MSBuildHelper.LocateMSBuild() in /home/runner/work/dotnet-please/dotnet-please/DotNetPlease/Helpers/MSBuildHelper.cs:line 535
   at DotNetPlease.Helpers.MSBuildHelper..cctor() in /home/runner/work/dotnet-please/dotnet-please/DotNetPlease/Helpers/MSBuildHelper.cs:line 87
```
I looked at the code and it [appeared that this had something to do with my dotnet SDKs](https://github.com/morganstanley/dotnet-please/blob/main/DotNetPlease/Helpers/MSBuildHelper.cs#L528). I listed them, and this was the result:
```
$ dotnet --list-sdks
2.1.818 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]
8.0.104 [C:\Program Files\dotnet\sdk]
8.0.204 [C:\Program Files\dotnet\sdk]
8.0.205 [C:\Program Files\dotnet\sdk]
```

Since it was a parsing error, I uninstalled the preview SDK, and sure enough the crash was fixed.

Easy to workaround but I thought it worth raising. Let me know if you need any more information for a repro.

**Comment by psmulovics** [comment]
Ah, great point, thank you for raising this! We would look at this ASAP.

**Comment by psmulovics** [comment]
So the good news, this was spotted by us and fixed earlier, but we never released a version with this fix, let us get to this now.

**Comment by jwm01cg** [comment]
Ah - good to hear! I probably should've spotted 08e7baf45e1ccc848af81aea49835a08dfb018a2 was the last commit at the top of the file I was analyzing. Thank you for the quick response.

**Comment by psmulovics** [comment]
So please do pick up https://www.nuget.org/packages/MorganStanley.DotNetPlease/3.0.0 :)
